name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: cursor-mate
  RUST_BACKTRACE: 1

permissions:
  contents: write

jobs:
  build-release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: cursor-mate-${{ github.ref_name }}-windows-x64.zip
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: cursor-mate-${{ github.ref_name }}-macos-x64.tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: cursor-mate-${{ github.ref_name }}-macos-arm64.tar.gz
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          
      - name: Package artifacts
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../../../${{ matrix.artifact_name }} cursor-mate.exe
          else
            tar -czf ../../../${{ matrix.artifact_name }} cursor-mate
          fi
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./${{ matrix.artifact_name }}
          retention-days: 1

  publish-release:
    needs: build-release
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加权限声明
    steps:
      - uses: actions/checkout@v3
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*
          body: |
            Release ${{ github.ref_name }}
            
            ## 支持平台
            - Windows (x64)
            - macOS (Intel x64)
            - macOS (Apple Silicon)
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

